name: docker image build and push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reponsitory code
        uses: actions/checkout@v2
      - name: docker image build
        run: dokcer build -t jkl836/flask-redis:latest .
      - name: list docker image
        run: docker image ls
      - name: dockerhub login
        run: docker login -u jkl836 -p
